# arguments for dataset
dataset: pretrain_mt
# nclass: 16
nclass: 22
rd_classes: 15
crop_size: 512
# data_root: '/data1/users/zhengzhiyu/ssl_workplace/dataset/ssl_pretrain/'
data_root: '/data2/users/yangcong2/sslworkplace/dataset/'
total_iters: 120000
lr: 0.00005
batch_size: 8
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 4
ignore_index: 255
validate_interval: 4000
log_interval: 100
save_interval: 20000
# eval_mode: original
eval_mode: resize
mask_ratio: 0.75