# arguments for dataset
dataset: AIRPolarSARSeg
nclass: 6
crop_size: 512
data_root: '/data1/users/zhengzhiyu/ssl_workplace/dataset/ssl_pretrain/'
mask_ratio: 0.5
epochs: 100
batch_size: 12 # per GPU x 4 GPUs
lr: 0.00005
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 255
IoU_threshod: 70
eval_mode: original
peft: lora


