# arguments for dataset
dataset: IRSAMap
nclass: 7
crop_size: 512
# crop_size: 518
data_root: '/data1/users/zhengzhiyu/mtp_workplace/dataset/MOTA/split_ss_dota1_0/'
epochs: 200
batch_size: 12 # per GPU x 4 GPUs
lr: 0.00005
lr_multi: 1.0

criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 255
eval_mode: resize