# arguments for dataset
dataset: isaid_ori
nclass: 16
crop_size: 512
data_root: '/data1/users/zhengzhiyu/mtp_workplace/dataset/MOTA/split_ss_dota1_0/'

# arguments for training
epochs: 150
batch_size: 2 # per GPU x 4 GPUs
lr: 0.00005
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 255
PATCH_SIZE: 32
MAX_RATIO: 0.75
# IoU_threshod: 56
warm_up: 30
eval_mode: resize

model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]