# arguments for dataset
dataset: OpenEarthMap
nclass: 9
crop_size: 512
# crop_size: 518
data_root: '/data1/users/zhengzhiyu/ssl_workplace/dataset/ssl_pretrain/'
epochs: 200
batch_size: 8 # per GPU x 4 GPUs
lr: 0.00005
lr_multi: 1.0

criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 255
eval_mode: resize

model: dpt
backbone: dinov2_base
lock_backbone: False