# arguments for dataset
dataset: oscd
nclass: 2
crop_size: 224
data_root: /data1/users/zhengzhiyu/mtp_workplace/dataset/oscd_rgb_patch_dataset/

# arguments for training
epochs: 100
batch_size: 16 # per GPU x 1 GPU
lr: 0.00005
