# arguments for dataset
dataset: potsdam
nclass: 5
crop_size: 512
data_root: '/data1/users/zhengzhiyu/ssl_workplace/dataset/ssl_pretrain/'
epochs: 100
batch_size: 12 # per GPU x 4 GPUs
lr: 0.00005
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 5
conf_thresh: 0.95
amp: False
workers: 1
ignore_index: 5
eval_mode: original


model: dpt
backbone: dinov2_base
lock_backbone: False