dataset: rscd
nclass: 2
epochs: 400
crop_size: 256
batch_size: 16
lr: 0.00005
lr_multi: 1.0
workers: 1
amp: True


levir:
  dataset: levir
  data_root: /data1/users/zhengzhiyu/mtp_workplace/dataset/LEVIR-CD256/
  nclass: 2
  crop_size: 256
  ignore_index: 255
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255

whu:
  dataset: whu
  data_root: /data1/users/zhengzhiyu/mtp_workplace/dataset/WHU-CD-256/
  nclass: 2
  crop_size: 256
  ignore_index: 255
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255


oscd:
  dataset: oscd
  data_root: /data1/users/zhengzhiyu/mtp_workplace/dataset/oscd_rgb_patch_dataset/
  nclass: 2
  crop_size: 256
  ignore_index: 255
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255
