dataset: rsseg
nclass: 9
epochs: 100
crop_size: 512
batch_size: 6
lr: 0.00005
lr_multi: 1.0
workers: 1
amp: True
data_root: '/data1/users/zhengzhiyu/ssl_workplace/dataset/ssl_pretrain/'
# eval_mode: original
# ignore_index: 5
# nclass: 5

vaihingen:
  dataset: vaihingen
  nclass: 5
  crop_size: 512
  ignore_index: 5
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 5

potsdam:
  dataset: potsdam
  nclass: 5
  crop_size: 512
  ignore_index: 5
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 5

OpenEarthMap:
  dataset: OpenEarthMap
  nclass: 9
  crop_size: 512
  ignore_index: 255
  eval_mode: resize
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255

loveda:
  dataset: loveda
  nclass: 7
  crop_size: 512
  ignore_index: 255
  eval_mode: resize
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255

UDD:
  dataset: UDD
  nclass: 6
  crop_size: 512
  ignore_index: 255
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255

VDD:
  nclass: 7
  crop_size: 512
  ignore_index: 255
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255

uavid:
  dataset: uavid
  nclass: 8
  crop_size: 512
  ignore_index: 255
  eval_mode: original
  criterion:
    name: CELoss
    kwargs:
      ignore_index: 255
