# arguments for dataset
dataset: uavid
nclass: 8
crop_size: 512
# crop_size: 518
data_root: '/data1/users/zhengzhiyu/ssl_workplace/dataset/ssl_pretrain/'

# arguments for training
epochs: 50
batch_size: 12 # per GPU x 4 GPUs
lr: 0.00005
# lr: 0.0001
lr_multi: 1.0
# lr_multi: 40
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 255
PATCH_SIZE: 32
MAX_RATIO: 0.5

eval_mode: original