# arguments for dataset
dataset: whu
nclass: 2
crop_size: 256
data_root: /data1/users/zhengzhiyu/mtp_workplace/dataset/WHU-CD-256/

# arguments for training
epochs: 200
batch_size: 16 # per GPU x 1 GPU
lr: 0.00005
